# Linear evaluation config for Capture-24 HAR
# data
crop_duration: null
crop_stride: null
# model architecture
use_register: True
attn_pooling: True
layer_scale_eps: 0.
bias: False
dropout: 0.
frozen: True
# training
epochs: 50
batch_size: 256
learning_rate: 1.0e-3
final_learning_rate: 1.0e-3
learning_rate_warmup_steps: 0
weight_decay: 1.0e-1
opt_betas: [0.9, 0.999]
gradient_clip: 1.
early_stopping_patience: 10
