run:
  amp: bfloat16
  compile: false
  checkpoint: null
  out_dir: results/pretrain/ViTB_capture24/m0.35_b10_p10
sampling_frequency: 100
channels:
- x
- y
- z
channel_size: 1000
patch_size: 10
min_block_size: 10
min_keep_ratio: 0.15
max_keep_ratio: 0.35
datasets:
  capture-24:
    path: /group-volume/datasets/openDB/Capture24
    split: train
    weight: 1.0
dim: 768
depth: 12
num_heads: 12
pred_dim: 384
pred_depth: 12
pred_num_heads: 12
mlp_ratio: 4.0
qkv_bias: false
dropout: 0.0
attn_dropout: 0.0
num_registers: 1
bias: false
norm_eps: 1.0e-06
layer_scale_eps: 0.0
epochs: 50
batch_size: 1024
encoder_momentum: 0.998
final_encoder_momentum: 0.9995
learning_rate: 0.001
final_learning_rate: 1.0e-06
learning_rate_warmup_ratio: 0.05
weight_decay: 0.01
final_weight_decay: 0.1
opt_betas:
- 0.9
- 0.99
opt_eps: 1.0e-06
gradient_clip: 0
gradient_accumulation_steps: 1
checkpoint_interval: 10000
